### ISSUE TITLE
WOL on iPad with iOS 9.3+ doesn't work

### ISSUE THREAD

**Issue by Klaus1189** [joethefox/Unofficial-Official-XBMC-Remote#72] opened 2016-06-10 17:25 UTC
I use the official iOS Kodi Remote App v1.5.5. I upgraded to iOS 9.3 and cannot wake up my Windows 10 Pro computer with the app.

But I can wake up my computer with my FRITZ!Box. In Webinterface of the FRITZ!Box there is a button called "wake up" and it works. So is this a known issue of the app, or am I doing something wrong. In the past the app worked great for me.

http://forum.kodi.tv/showthread.php?tid=266328

I tried also Kore on my Android 6.0.1 phone which works fine.

**Comment by joethefox** [comment] 2016-06-13 09:21
closed. duplicate of https://github.com/joethefox/Unofficial-Official-XBMC-Remote/issues/54

**Closed by joethefox** 2016-06-13 09:21 UTC
